app/web/router.ex
defmodule Sense.Router do
  use Sense.Web, :router
  use Plug.ErrorHandler

  defp handle_errors(conn, %{kind: kind, reason: reason, stack: stacktrace}) do
    Rollbax.report(kind, reason, stacktrace, %{method: conn.method})
  end

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :with_session do
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
    plug Sense.CurrentUser
  end

  pipeline :session_required do
    plug Guardian.Plug.EnsureAuthenticated, handler: Sense.GuardianErrorHandler
  end

  scope "/mqtt", Sense do
    post "/user", MqttAuthenticatorController, :user
    post "/superuser", MqttAuthenticatorController, :superuser
    post "/acl", MqttAuthenticatorController, :acl
  end

  scope "/", Sense do
    pipe_through [:browser, :with_session]

    get "/", PageController, :index
    resources "/users", UserController, only: [:new, :create]
    resources "/sessions", SessionController, only: [:new, :create, :delete]
  end

  scope "/", Sense do
    pipe_through [:browser, :with_session, :session_required]

    resources "/users", UserController, only: [:show]
  end

  # API Scope
  scope "/api", Sense.Api, as: :api do
    pipe_through [:api]

    scope "/v1", V1, as: :v1 do
      resources "/user", UserController, only: [:delete, :update, :show, :create], singleton: true
      resources "/devices", DeviceController, except: [:new, :edit] do
        resources "/actuators", ActuatorController, except: [:new, :edit]
        resources "/metrics", MetricController, except: [:new, :edit] do
          resources "/measures", MeasureController, only: [:index, :create]
          delete "/measures", MeasureController, :delete
        end
      end
    end
  end
end

app/web/views/layout_view.ex
defmodule Sense.LayoutView do
  use Sense.Web, :view
end

app/web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Sense!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">
            <%= if @current_user do %>
            <li><%= @current_user.email %> (<%= @current_user.id %>)</li>
            <li>
              <%= link "Sign out", to: session_path(@conn, :delete,
                  @current_user),
                  method: "delete" %>
            </li>
            <% else %>
            <li><%= link "Register", to: user_path(@conn, :new) %></li>
            <li><%= link "Sign in", to: session_path(@conn, :new) %></li>
            <% end %>
        </nav>
        <span class="logo"></span>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>